### ISSUE TITLE
Support linux/arm64/v8 for docker (mac, apple silicons)

### ISSUE THREAD

**Issue by iloahz** [duyet/clickhouse-monitoring#444]
Would be nice to support arm, so we can run on mac

```
[+] Running 0/1
 ⠙ clickhouse-monitoring Pulling                                                                                                                       2.1s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by duyet** [comment]
I have updated and please help me test with the latest image:

```bash
docker pull ghcr.io/duyet/clickhouse-monitoring:main
```

**Comment by ppetruneac** [comment]
@duyet Thanks for your support on this. 

I have 

```
export DOCKER_DEFAULT_PLATFORM=linux/arm64
docker pull ghcr.io/duyet/clickhouse-monitoring:main 
```

I have the image: 
```
  ❯ docker image ls | grep monit
ghcr.io/duyet/clickhouse-monitoring                                   main              7049dca97f30   7 hours ago     229MB
```

Here is my docker-compose: 
```
services:

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9001:9001
      - 9000:9000
    environment:
      - RUN_INITDB_SCRIPTS=1
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TIMEZONE=Europe/Bucharest
      - MAX_SERVER_MEMORY_USAGE=22000000000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    
  clickhouse_ui:
    image: ghcr.io/caioricciuti/ch-ui
    container_name: clickhouse_ui
    ports:
      - 5521:5521
    environment:
      - VITE_CLICKHOUSE_URL=http://localhost:8123
      - VITE_CLICKHOUSE_USER=clickhouse
      - VITE_CLICKHOUSE_PASS=clickhouse

  clickhouse_monitoring:
    image: ghcr.io/duyet/clickhouse-monitoring
    container_name: clickhouse_monitoring
    ports:
      - 3000:3000
    environment:
      - CLICKHOUSE_HOST=http://localhost:8123
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASS=clickhouse      
      - CLICKHOUSE_MAX_EXECUTION_TIME=15
      - CLICKHOUSE_QUERY_CACHE_TTL=86400
 
```

getting: 

> no matching manifest for linux/arm64 in the manifest list entries
